export const VIEW_NAV = "VIEW_NAV"
export const VIEW_FOOT = "VIEW_FOOT"
export const VIEW_LOADING = "VIEW_LOADING"
export const UPDATA_HOME = "UPDATA_HOME"
export const UPDATA_FOLLOW = "UPDATA_FOLLOW"
export const UPDATA_DETAIL = "UPDATA_DETAIL"
export const UPDATA_BANNER = "UPDATA_BANNER"
export const UPDATA_USER = "UPDATA_USER"
export const ERR_LOGIN_MESS = "ERR_LOGIN_MESS"
export const ERR_REG_MESS = "ERR_REG_MESS"
export const COLLECTION_LIST = "COLLECTION_LIST"

